import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import BaseClientProvider from "./provider/BaseClientProvider";
import BaseServerProvider from "./provider/BaseServerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaseServerProvider>
          <BaseClientProvider>{children}</BaseClientProvider>
        </BaseServerProvider>
      </body>
    </html>
  );
}
